apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-logs-pv
  labels:
    app: sda-training
    component: logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-static
  hostPath:
    path: /tmp/sda-training/app-logs
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-uploads-pv
  labels:
    app: sda-training
    component: uploads
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-static
  hostPath:
    path: /tmp/sda-training/app-uploads
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv
  labels:
    app: sda-training
    component: mongodb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-static
  hostPath:
    path: /tmp/sda-training/mongodb
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
  labels:
    app: sda-training
    component: postgresql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-static
  hostPath:
    path: /tmp/sda-training/postgresql
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  labels:
    app: sda-training
    component: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-static
  hostPath:
    path: /tmp/sda-training/prometheus
    type: DirectoryOrCreate