apiVersion: v1
kind: Secret
metadata:
  name: sda-training-secrets
  namespace: sda-training
type: Opaque
data:
  JWT_SECRET: ZGF5MTctZGV2LWp3dC1zZWNyZXQ=
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9zZGFfdHJhaW5pbmc/YXV0aFNvdXJjZT1hZG1pbg==
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL3NkYV90cmFpbmluZw==
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=